repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ ./app/, --fix, --config, ./app/pyproject.toml ]
    # Run the formatter
    - id: ruff-format
      args: [ ./app/, --config, ./app/pyproject.toml ]