services:

  web:
    build:
      context: .
      dockerfile: ./compose/dev/web/Dockerfile
      args:
        - BUILD_ENVIRONMENT=dev  # dev|production
    container_name: qr_buddies_web
    image: qr_buddies_web
    privileged: false
    volumes:
      - ./app:/app:z
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - ./app/.env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  
  valkey:
    image: docker.io/valkey/valkey:7.2-alpine
    container_name: qr_buddies_valkey
    command: valkey-server /etc/valkey/valkey.conf
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ./compose/dev/valkey/valkey.conf:/etc/valkey/valkey.conf
    ports:
      - "6379:6379"
    restart: unless-stopped
