services:

  nginx:
    build: ./compose/production/nginx/
    volumes:
      - static_volume:/app/static
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qrbuds.tls.certresolver=production"
      - "traefik.http.routers.qrbuds.tls=true"
      - "traefik.http.routers.qrbuds.entrypoints=web,websecure"
      - "traefik.http.routers.qrbuds.rule=Host(`chat.bacovsky.online`) || Host(`www.chat.bacovsky.online`)"
      - "traefik.http.routers.qrbuds.middlewares=redirect-www@file"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        - BUILD_ENVIRONMENT=production  # dev|production
    container_name: qr_buddies_web
    image: qr_buddies_web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - web_db:/app/data
    networks:
      - traefik-proxy
    restart: unless-stopped
    depends_on:
      valkey:
        condition: service_healthy
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             daphne -b 0.0.0.0 -p 9001 qr_buddies.asgi:application"
             
  
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: qr_buddies_valkey
    command: valkey-server /etc/valkey/valkey.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ./compose/production/valkey/valkey.conf:/etc/valkey/valkey.conf
    networks:
      - traefik-proxy
    restart: unless-stopped

volumes:
  web_db:
  static_volume:
  media_volume:


networks:
  traefik-proxy:
    external: true
