on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:24-bookworm-slim
    services:
      valkey:
        image: valkey/valkey
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Install OS dependencies
        run: |
          apt-get update && 
          apt-get install python3-virtualenv redis-server --no-install-recommends -y

      - name: Setup app virtual environment
        run: |
          mkdir venv && virtualenv venv
          source venv/bin/activate
          pip install -r app/requirements/dev.txt

      - name: Run tests
        env:
          ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          VALKEY_HOST: localhost
          VALKEY_PORT: 6379
        run: |
          source venv/bin/activate
          cd app && coverage run -m pytest -v . && coverage report
