on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: https://data.forgejo.org/actions/checkout@v6

      - name: Install OS dependencies
        run: |
          sudo apt-get update && 
          sudo apt-get install python3-virtualenv --no-install-recommends -y

      - name: Setup app virtual environment
        run: |
          mkdir venv && virtualenv venv
          source venv/bin/activate
          pip install -r app/requirements/dev.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          cd app && coverage run -m pytest -v . && coverage report
