# Generated by Django 4.2.14 on 2024-07-18 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qr_pair", "0002_alter_qrcode_pair"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QRMatch",
            new_name="ChatRoom",
        ),
    ]
