# Generated by Django 4.2.14 on 2024-07-18 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qr_pair", "0003_rename_qrmatch_chatroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcode",
            old_name="pair",
            new_name="chat_room",
        ),
    ]
